### ISSUE TITLE
Multiple images (variety exposure) -> one ground truth

### ISSUE THREAD

**Issue by dat-lequoc** [LiuZhu-CV/CRMEF#3]
Hello,

Thank you very much for the great work!

I'm curious about how I can modify the architecture to adapt to my use case. I have 5 images with different exposures of the same scene, and the ground truth is the merged result of these images. I want to train a model to perform this mapping, but the current architecture only receives one underexposed (UE) and one overexposed (OE) image.

How can I modify the architecture to handle multiple images with different exposures?

Thank you!

**Comment by LiuZhu-CV** [comment]
(1) You can add a task encoder that handles different exposures and merge these features. (2) You can process in stages, processing only two images at a time.
