### ISSUE TITLE
Potential Application for Other Image Fusion Tasks?

### ISSUE THREAD

**Issue by AllenJRZhang** [LiuZhu-CV/CRMEF#4]
This is an exciting read! 

After reading the paper, I'd like to ask if this method can potentially be used for other image fusion tasks, such as Multi-Focus Image Fusion, Multi-Image Super Resolution, and so on? Or perhaps a combination of several of these tasks, like that in U2Fusion, for example?

Please correct me if I'm wrong, but since it appears to me that the core components are the self alignment module and feature depletion module, in theory the same architecture would transfer well to similar image fusion objectives, like the ones I mentioned above, right? 

Just a thought, I'm looking forward to your input. Thanks a lot.

**Comment by JinyuanLiu-CV** [comment]
Yes, you can leverage these modules to address other fusion tasks by designing some task-specific architectures
